### ISSUE TITLE
Compilation error on Ubuntu

### ISSUE THREAD

**Issue by NeoMahler** [Matt-Fitzpatrick/etoh-downloader#2]
I get the following error:
```
gcc -O3 -Wall   -c -o etoh-downloader.o etoh-downloader.c
etoh-downloader.c:13:10: fatal error: libxml2/tree.h: El fitxer o directori no existeix
 #include <libxml2/tree.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'etoh-downloader.o' failed
make: *** [etoh-downloader.o] Error 1
```
(note: the error message in Catalan translates to "file or directory does not exist"). I tried the solution in #1, creating a symlink, but it doesn't seem to work.

**Comment by cdayjr** [comment]
I gave this a shot in Ubuntu 18.10- I had to make a symlink but it compiles fine for me.

**Comment by Matt-Fitzpatrick** [comment]
Just dropping a note to self, possible Makefile fixes in https://stackoverflow.com/questions/20889799/fatal-error-libxml-tree-h-no-such-file-or-directory-libxml-tree-h-in-cyrus-im

**Comment by Matt-Fitzpatrick** [comment]
The edit I made to Makefile, to use xml2-config, seems promising. Is it working now?

**Comment by cdayjr** [comment]
Just gave the new Makefile a shot on my Fedora 30 and Ubuntu 18.10 installs without a symlink for xmllib2- works great! No issues here.

**Comment by Matt-Fitzpatrick** [comment]
Appears to be fixed, but please let us know if there continue to be problems.
