### ISSUE TITLE
Checksums fail for some servers

### ISSUE THREAD

**Issue by rosshadden** [Matt-Fitzpatrick/etoh-downloader#4]
The downloader works great for me for Homecoming, but for Rebirth and coxg the checksums fail on the first file it tries to download.

**Comment by Matt-Fitzpatrick** [comment]
This manifest?

[https://www.cohreborn.com/manifest/pleiadesmanifest.xml](https://www.cohreborn.com/manifest/pleiadesmanifest.xml)

**Comment by Matt-Fitzpatrick** [comment]
Confirmed, working on a patch now. Thanks for the report!

**Comment by Matt-Fitzpatrick** [comment]
Patch committed, please let me know if it works for you.

**Comment by Matt-Fitzpatrick** [comment]
Seems to have been a simple case sensitivity bug. Works on my machine, so I'll close this for now. Let me know if there are any further issues. Thanks!
